FROM public.ecr.aws/lambda/python:3.13

COPY src/fetch_and_ingest.py ${LAMBDA_TASK_ROOT}/src/
COPY src/__init__.py ${LAMBDA_TASK_ROOT}/src/

RUN pip install psycopg2-binary python-dotenv requests

CMD ["src.fetch_and_ingest.handler"]
