FROM python:3.13-slim

WORKDIR /app

COPY src/dashboard.py /app
COPY assets/ /app/assets
RUN pip install streamlit requests pandas plotly

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]