FROM python:3.13-slim

WORKDIR /app

COPY src/fetch_and_ingest.py /app/src/
COPY src/api.py /app/src/
COPY src/models.py /app/src/
COPY src/__init__.py /app/src

RUN pip install psycopg2-binary fastapi[standard] python-dotenv requests

CMD ["fastapi", "run", "src/api.py", "--host", "0.0.0.0", "--port", "8000"]